name = "movie"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
browser = { binding = "MYBROWSER" }
kv_namespaces = [
  { binding = "BROWSER_KV_DEMO", id = "15db9f5e46594a5b8ca0693f037257e5", preview_id = "feefadff24e3492e8679b33dd567a11b" }
]
pages_build_output_dir = ".vercel/output/static"